In [1]:
import numpy as np 
import pandas as pd

In [4]:
data=pd.read_csv("../archive/all_season_batting_card.csv")

In [5]:
data.head()

,season,match_id,match_name,home_team,away_team,venue,city,country,current_innings,innings_id,...,fours,sixes,strikeRate,captain,isNotOut,runningScore,runningOver,shortText,commentary,link
0,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,CSK,1,...,3.0,1.0,118.51,False,False,"{'wickets': 1, 'runs': 61}",8.1,c Shivam Mavi b Narine,"<strong>dances down, and slices to long-off!</...",NaN
1,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,CSK,1,...,7.0,3.0,145.76,False,False,"{'wickets': 3, 'runs': 192}",19.6,c Iyer b Shivam Mavi,he's holed out to long-on! <B> Won't get the o...,NaN
2,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,CSK,1,...,0.0,3.0,206.66,False,False,"{'wickets': 2, 'runs': 124}",13.3,lbw b Narine,<strong>big appeal for lbw and given by umpire...,NaN
3,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,CSK,1,...,2.0,3.0,185.00,False,True,{},NaN,not out,NaN,NaN
4,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,KKR,2,...,6.0,0.0,118.60,False,False,"{'wickets': 4, 'runs': 108}",13.2,lbw b Chahar,<strong>brain fade or what?</strong> Gill is s...,NaN

In [42]:
data.drop(data[data['season'] <= 2017].index, inplace = True)

In [6]:
data.head()

,season,match_id,match_name,home_team,away_team,venue,city,country,current_innings,innings_id,...,fours,sixes,strikeRate,captain,isNotOut,runningScore,runningOver,shortText,commentary,link
0,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,CSK,1,...,3.0,1.0,118.51,False,False,"{'wickets': 1, 'runs': 61}",8.1,c Shivam Mavi b Narine,"<strong>dances down, and slices to long-off!</...",NaN
1,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,CSK,1,...,7.0,3.0,145.76,False,False,"{'wickets': 3, 'runs': 192}",19.6,c Iyer b Shivam Mavi,he's holed out to long-on! <B> Won't get the o...,NaN
2,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,CSK,1,...,0.0,3.0,206.66,False,False,"{'wickets': 2, 'runs': 124}",13.3,lbw b Narine,<strong>big appeal for lbw and given by umpire...,NaN
3,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,CSK,1,...,2.0,3.0,185.00,False,True,{},NaN,not out,NaN,NaN
4,2021,1254117,CSK v KKR,CSK,KKR,Dubai International Cricket Stadium,Dubai,United Arab Emirates,KKR,2,...,6.0,0.0,118.60,False,False,"{'wickets': 4, 'runs': 108}",13.2,lbw b Chahar,<strong>brain fade or what?</strong> Gill is s...,NaN

In [7]:
data.columns

Index(['season', 'match_id', 'match_name', 'home_team', 'away_team', 'venue',
       'city', 'country', 'current_innings', 'innings_id', 'name', 'fullName',
       'runs', 'ballsFaced', 'minutes', 'fours', 'sixes', 'strikeRate',
       'captain', 'isNotOut', 'runningScore', 'runningOver', 'shortText',
       'commentary', 'link'],
      dtype='object')

In [45]:
data=data.drop(['match_id','match_name','home_team','away_team','venue','city','country','current_innings','innings_id','name','minutes','captain','runningScore','runningOver','shortText','commentary','link','strikeRate'],axis=1)

In [46]:
names=data['fullName'].unique()

In [90]:
runs2021=[]
ballsfaced2021=[]
fours2021=[]
sixes2021=[]
strikerate2021=[]

runs2020=[]
ballsfaced2020=[]
fours2020=[]
sixes2020=[]
strikerate2020=[]

runs2019=[]
ballsfaced2019=[]
fours2019=[]
sixes2019=[]
strikerate2019=[]

runs2018=[]
ballsfaced2018=[]
fours2018=[]
sixes2018=[]
strikerate2018=[]

runs2017=[]
ballsfaced2017=[]
fours2017=[]
sixes2017=[]
strikerate2017=[]

for i in range(len(names)):
    temp1=0
    temp2=0
    temp3=0
    temp4=0
    temp5=0
    for ri,rd in data.iterrows():
        if(rd['fullName']==names[i])and(rd['season']==2021):
            temp1+=rd['runs']
            temp2+=rd['ballsFaced']
            temp3+=rd['fours']
            temp4+=rd['sixes']
    runs2021.append(temp1)
    ballsfaced2021.append(temp2)
    fours2021.append(temp3)
    sixes2021.append(temp4)
    if(temp2==0):
        strikerate2021.append(0)
    else:
        strikerate2021.append(temp1*100/temp2)

for i in range(len(names)):
    temp1=0
    temp2=0
    temp3=0
    temp4=0
    temp5=0
    for ri,rd in data.iterrows():
        if(rd['fullName']==names[i])and(rd['season']==2020):
            temp1+=rd['runs']
            temp2+=rd['ballsFaced']
            temp3+=rd['fours']
            temp4+=rd['sixes']
    runs2020.append(temp1)
    ballsfaced2020.append(temp2)
    fours2020.append(temp3)
    sixes2020.append(temp4)
    if(temp2==0):
        strikerate2020.append(0)
    else:
        strikerate2020.append(temp1*100/temp2)

for i in range(len(names)):
    temp1=0
    temp2=0
    temp3=0
    temp4=0
    temp5=0
    for ri,rd in data.iterrows():
        if(rd['fullName']==names[i])and(rd['season']==2019):
            temp1+=rd['runs']
            temp2+=rd['ballsFaced']
            temp3+=rd['fours']
            temp4+=rd['sixes']
    runs2019.append(temp1)
    ballsfaced2019.append(temp2)
    fours2019.append(temp3)
    sixes2019.append(temp4)
    if(temp2==0):
        strikerate2019.append(0)
    else:
        strikerate2019.append(temp1*100/temp2)
        

for i in range(len(names)):
    temp1=0
    temp2=0
    temp3=0
    temp4=0
    temp5=0
    for ri,rd in data.iterrows():
        if(rd['fullName']==names[i])and(rd['season']==2018):
            temp1+=rd['runs']
            temp2+=rd['ballsFaced']
            temp3+=rd['fours']
            temp4+=rd['sixes']
    runs2018.append(temp1)
    ballsfaced2018.append(temp2)
    fours2018.append(temp3)
    sixes2018.append(temp4)
    if(temp2==0):
        strikerate2018.append(0)
    else:
        strikerate2018.append(temp1*100/temp2)


for i in range(len(names)):
    temp1=0
    temp2=0
    temp3=0
    temp4=0
    temp5=0
    for ri,rd in data.iterrows():
        if(rd['fullName']==names[i])and(rd['season']==2017):
            temp1+=rd['runs']
            temp2+=rd['ballsFaced']
            temp3+=rd['fours']
            temp4+=rd['sixes']
    runs2017.append(temp1)
    ballsfaced2017.append(temp2)
    fours2017.append(temp3)
    sixes2017.append(temp4)
    if(temp2==0):
        strikerate2017.append(0)
    else:
        strikerate2017.append(temp1*100/temp2)

In [105]:
d={"Name":names,"runs":runs2021,"balls":ballsfaced2021, "fours":fours2021,"sixes":sixes2021,"sr":strikerate2021}
data2021=pd.DataFrame(d)
data2021

                Name   runs  balls  fours  sixes          sr
0    Ruturaj Gaikwad  635.0  466.0   64.0   23.0  136.266094
1     Faf du Plessis  633.0  458.0   60.0   23.0  138.209607
2      Robin Uthappa  115.0   84.0    8.0    5.0  136.904762
3          Moeen Ali  357.0  260.0   31.0   19.0  137.307692
4       Shubman Gill  478.0  402.0   50.0   12.0  118.905473
..               ...    ...    ...    ...    ...         ...
235      Karn Sharma    0.0    0.0    0.0    0.0    0.000000
236       Naman Ojha    0.0    0.0    0.0    0.0    0.000000
237  Prashant Chopra    0.0    0.0    0.0    0.0    0.000000
238    Javon Searles    0.0    0.0    0.0    0.0    0.000000
239    Anureet Singh    0.0    0.0    0.0    0.0    0.000000

[240 rows x 6 columns]

In [106]:
d={"Name":names,"runs":runs2020,"balls":ballsfaced2020,"fours":fours2020,"sixes":sixes2020,"sr":strikerate2020}
data2020=pd.DataFrame(d)
data2020

                Name   runs  balls  fours  sixes          sr
0    Ruturaj Gaikwad  204.0  169.0   16.0    6.0  120.710059
1     Faf du Plessis  449.0  319.0   42.0   14.0  140.752351
2      Robin Uthappa  196.0  164.0   19.0    7.0  119.512195
3          Moeen Ali   12.0   16.0    1.0    0.0   75.000000
4       Shubman Gill  440.0  373.0   44.0    9.0  117.962466
..               ...    ...    ...    ...    ...         ...
235      Karn Sharma    0.0    0.0    0.0    0.0    0.000000
236       Naman Ojha    0.0    0.0    0.0    0.0    0.000000
237  Prashant Chopra    0.0    0.0    0.0    0.0    0.000000
238    Javon Searles    0.0    0.0    0.0    0.0    0.000000
239    Anureet Singh    0.0    0.0    0.0    0.0    0.000000

[240 rows x 6 columns]

In [107]:
d={"Name":names,"runs":runs2019,"balls":ballsfaced2019,"fours":fours2019,"sixes":sixes2019,"sr":strikerate2019}
data2019=pd.DataFrame(d)
data2019

                Name   runs  balls  fours  sixes          sr
0    Ruturaj Gaikwad    0.0    0.0    0.0    0.0    0.000000
1     Faf du Plessis  396.0  321.0   36.0   15.0  123.364486
2      Robin Uthappa  282.0  245.0   28.0   10.0  115.102041
3          Moeen Ali  220.0  133.0   16.0   17.0  165.413534
4       Shubman Gill  296.0  238.0   21.0   10.0  124.369748
..               ...    ...    ...    ...    ...         ...
235      Karn Sharma    0.0    0.0    0.0    0.0    0.000000
236       Naman Ojha    0.0    0.0    0.0    0.0    0.000000
237  Prashant Chopra    0.0    0.0    0.0    0.0    0.000000
238    Javon Searles    0.0    0.0    0.0    0.0    0.000000
239    Anureet Singh    0.0    0.0    0.0    0.0    0.000000

[240 rows x 6 columns]

In [108]:
d={"Name":names,"runs":runs2018,"balls":ballsfaced2018,"fours":fours2018,"sixes":sixes2018,"sr":strikerate2018}
data2018=pd.DataFrame(d)
data2018

                Name   runs  balls  fours  sixes          sr
0    Ruturaj Gaikwad    0.0    0.0    0.0    0.0    0.000000
1     Faf du Plessis  162.0  129.0   17.0    6.0  125.581395
2      Robin Uthappa  351.0  265.0   30.0   21.0  132.452830
3          Moeen Ali   77.0   46.0    4.0    6.0  167.391304
4       Shubman Gill  203.0  139.0   22.0    5.0  146.043165
..               ...    ...    ...    ...    ...         ...
235      Karn Sharma    0.0    0.0    0.0    0.0    0.000000
236       Naman Ojha    1.0    4.0    0.0    0.0   25.000000
237  Prashant Chopra    8.0    6.0    2.0    0.0  133.333333
238    Javon Searles    8.0    6.0    0.0    1.0  133.333333
239    Anureet Singh    3.0    4.0    0.0    0.0   75.000000

[240 rows x 6 columns]

In [109]:
d={"Name":names,"runs_2017":runs2017,"ballsfaced_2017":ballsfaced2017,"fours_2017":fours2017,"sixes_2017":sixes2017,"strikeRate_2017":strikerate2017}
data2017=pd.DataFrame(d)
data2017

,Name,runs_2017,ballsfaced_2017,fours_2017,sixes_2017,strikeRate_2017
0,Ruturaj Gaikwad,0,0,0,0,0
1,Faf du Plessis,0,0,0,0,0
2,Robin Uthappa,0,0,0,0,0
3,Moeen Ali,0,0,0,0,0
4,Shubman Gill,0,0,0,0,0
...,...,...,...,...,...,...
235,Karn Sharma,0,0,0,0,0
236,Naman Ojha,0,0,0,0,0
237,Prashant Chopra,0,0,0,0,0
238,Javon Searles,0,0,0,0,0
239,Anureet Singh,0,0,0,0,0

In [110]:
data2017.to_csv("data2017.csv")
data2018.to_csv("data2018.csv")
data2019.to_csv("data2019.csv")
data2020.to_csv("data2020.csv")
data2021.to_csv("data2021.csv")

In [111]:
data2020.isnull().sum()

Name     0
runs     0
balls    0
fours    0
sixes    0
sr       0
dtype: int64